export const homeObjTwo = {
    id: 'github',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'My Code',
    headline: 'Here are a few of my most recent works',
    description: 'These past projects below demonstrate my coding abilities in Solidity, React.js, Next.js, Javascript, CSS, HTML5 and more. To view all of my source codes, visit the link below!  ',
    buttonLabel: 'Access My Github',
    buttonAddress: "https://github.com/0xJozeth",
    imgStart: false,
    img: require('../../images/eth_1.svg'),
    alt: 'Ethereum',
    dark: false,
    primary: false,
    darkText: true,
};