export const homeObjSix = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Let\'s Connect',
    headline: 'Find Me On LinkedIn',
    description: 'Looking to bring your ideas to life? I\'d love to hear from you. Let\'s connect on LinkedIn.',
    buttonLabel: 'Visit My LinkedIn',
    imgStart: false,
    img: require('../../images/lost_svg_1.svg'),
    alt: 'Ethereum',
    dark: true,
    primary: true,
    darkText: true,
};