export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Get To Know Me',
    headline: "About Me",
    description: 'Blockchain engineer from Jacksonville, student of all things tech, hungry to develop my craft. Curiously adding value to the industry by specializing in building smart contracts on the Ethereum blockchain. A few technologies I\'ve been working with recently are:',
    descriptionList: 'Solidity, Javascript (ES6+), React, Wordpress, Node.js, Solana, and Rust.',
    buttonLabel: 'Get In Touch',
    imgStart: false,
    img: require('../../images/vr_svg_1.svg'),
    alt: 'aboutme',
    dark: true,
    primary: true,
    darkText: false,
};