export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: "About Me Section",
    description: 'I\'m a Jacksonville-based blockchain engineer who specializes in building smart contracts on the Ethereum blockchain. This is a collection of my past works in blockchain technology. A few technologies I\'ve been working with recently are Solidity, Javascript (ES6+), React, Wordpress, Node.js, Solana, and Rust.',
    buttonLabel: 'Get In Touch',
    imgStart: false,
    img: require('../../images/vr_svg_1.svg'),
    alt: 'aboutme',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'github',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'My Code',
    headline: 'Here are a few of my most recent works',
    description: 'These past projects below demonstrate my coding abilities in Solidity, React.js, Next.js, Javascript, CSS, HTML5 and more. To view all of my source codes, visit the link below!  ',
    buttonLabel: 'Access My Github',
    buttonAddress: "https://github.com/0xJozeth",
    imgStart: false,
    img: require('../../images/eth_1.svg'),
    alt: 'Ethereum',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'proficiencies',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Proficiencies',
    headline: 'A few of my strongest languages...',
    description: 'No matter how far along in my coding career, I will always be a student as the field evolves. Here are a few of the languages I have experience with.',
    buttonLabel: 'See Proficiencies',
    imgStart: false,
    img: require('../../images/programming_svg_1.svg'),
    alt: 'Ethereum',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjFour = {
    id: 'timeline',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Timeline',
    headline: 'A timeline of my accomplishments',
    description: "The journey of a thousand miles begins with a single step. Here's a list of my coding accomplishments.",
    buttonLabel: 'See Timeline',
    imgStart: false,
    img: require('../../images/programming_svg_1.svg'),
    alt: 'Ethereum',
    dark: true,
    primary: true,
    darkText: true,
};

export const homeObjFive = {
    id: 'tokens',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Tokens',
    headline: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum',
    description: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
    buttonLabel: 'See More',
    imgStart: false,
    img: require('../../images/programming_svg_1.svg'),
    alt: 'Ethereum',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjSix = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Let\'s Connect',
    headline: 'Find Me On LinkedIn',
    description: 'Looking to bring your ideas to life? I\'d love to hear from you. Let\'s connect on LinkedIn.',
    buttonLabel: 'Visit My LinkedIn',
    imgStart: false,
    img: require('../../images/lost_svg_1.svg'),
    alt: 'Ethereum',
    dark: true,
    primary: true,
    darkText: true,
};